swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Sign up
      description: API for Sign up
      parameters:
        - in: body
          name: body
          description: Sign up Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Sign up Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error         
  /transactions/user/{userID}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Get User Transactions History
      description: API for retrieving transactions history
      parameters:
        - name: userID
          in: path
          description: User ID
          required: true
          type: string
      #produces:
        #- application/json
      responses:
        '200':
          description: User account retrieved successfully
          schema:
            $ref: '#/definitions/UserAccount'
        '401':
          description: Unauthorized
        '400':
          description: User not found
        '500':
          description: Internal Server Error     
  /transactions/{transactionID}:
    get:
      security:
      - Bearer: []
      tags:
        - Transaction
      summary: Get An Transaction Detail
      description: API for fetching an transaction detail
      parameters:
        - name: transactionID
          in: path
          description: Transaction ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction information retrieved successfully
          schema:
            $ref: '#/definitions/UserTransaction'
        '401':
          description: Unauthorized
        '400':
          description: Invalid request
        '404':
          description: Transaction not found
    post:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Create Transaction 
      description: API for creating a new transaction 
      parameters:
        - name: transactionID
          in: path
          description: Transaction ID
          required: true
          type: string
      #produces:
        #- application/json
      responses:
        '200':
          description: User transaction detail created successfully
          schema:
            $ref: '#/definitions/UserTransaction'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
  /transactions/{transactionID}/category:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Update Transaction Category
      description: API for updating the category of an existing transaction 
      parameters:
        - name: transactionID
          in: path
          description: Transaction ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction detail updated successfully
          schema:
            $ref: '#/definitions/TransactionCategory'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  /transactions/{transactionID}/note:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Update Transaction Note
      description: API for updating the note of an existing transaction detail
      parameters:
        - name: transactionID
          in: path
          description: Transaction ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction detail updated successfully
          schema:
            $ref: '#/definitions/TransactionNote'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  UserAccount:
    type: object
    properties:
      id:
        type: string
        example: "string"
      name:
        type: string
        example: "string"
      status:
        type: string
        enum: [solvent, insolvent]
        description: Indication of the account balance
        example: "string"
      total:
        type: number
        format: double
        example: "number"
      transactions:
          type: object
          properties:
            id:
              type: number
              example: "number"
  UserTransaction:
    type: array
    items: 
      type: object
      properties:
        id:
          type: string
          example: "number"
        date:
          type: string
          format: date-time
          example: "date-time"
        description:
          type: string
          example: "string"
        amount:
          type: number
          format: double
          example: "number"
        balance:
          type: number
          format: double
          example: "number"
        body:
          type: object
          properties:
            transactionType: 
              type: string
              example: "string"
            category: 
              type: string
              example: "string"
            note:
              type: string
              example: "string"
  TransactionCategory:
    type: object
    properties:
      category:
        type: string
        description: Message indication the success of the operation
        
  TransactionNote:
    type: object
    properties:
      description:
        type: string
      
    
                    
  
